using Koopman.CheckPoint;
using Koopman.CheckPoint.FastUpdate;
using System.Management.Automation;
using System.Threading.Tasks;

namespace psCheckPoint.Objects.Application
{
    /// <api cmd="set-application-site">Set-CheckPointApplication</api>
    /// <summary>
    /// <para type="synopsis">Edit existing object using object name or uid.</para>
    /// <para type="description"></para>
    /// </summary>
    /// <example></example>
    [Cmdlet(VerbsCommon.Set, "CheckPointApplication")]
    [OutputType(typeof(Koopman.CheckPoint.ApplicationSite))]
    public class SetCheckPointApplication : SetCheckPointCmdlet
    {
        #region Fields

        private string[] _additionalCategories;
        private string[] _applicationSignatures;
        private string[] _groups;
        private string[] _urlList;

        #endregion Fields

        #region Properties

        /// <summary>
        /// <para type="description">
        /// Used to configure or edit the additional categories of a custom application / site used
        /// in the Application and URL Filtering or Threat Prevention.
        /// </para>
        /// </summary>
        [Parameter(ValueFromPipelineByPropertyName = true)]
        public string[] AdditionalCategories { get => _additionalCategories; set => _additionalCategories = CreateArray(value); }

        /// <summary>
        /// <para type="description">Action to take with Additional Categories.</para>
        /// </summary>
        [Parameter]
        public MembershipActions AdditionalCategoriesAction { get; set; } = MembershipActions.Replace;

        /// <summary>
        /// <para type="description">Application signature generated by Signature Tool.</para>
        /// </summary>
        [Parameter(ValueFromPipelineByPropertyName = true)]
        public string[] ApplicationSignature { get => _applicationSignatures; set => _applicationSignatures = CreateArray(value); }

        /// <summary>
        /// <para type="description">Action to take with Application Signatures.</para>
        /// </summary>
        [Parameter]
        public MembershipActions ApplicationSignatureAction { get; set; } = MembershipActions.Replace;

        /// <summary>
        /// <para type="description">Group object, name or UID.</para>
        /// </summary>
        [Parameter(Mandatory = true, ValueFromPipelineByPropertyName = true, ValueFromPipeline = true, ValueFromRemainingArguments = true)]
        [Alias("Name", "UID")]
        public PSObject ApplicationSite { get => Object; set => Object = value; }

        /// <summary>
        /// <para type="description">A description for the application.</para>
        /// </summary>
        [Parameter(ValueFromPipelineByPropertyName = true)]
        public string Description { get; set; }

        /// <summary>
        /// <para type="description">Action to take with groups.</para>
        /// </summary>
        [Parameter]
        public MembershipActions GroupAction { get; set; } = MembershipActions.Replace;

        /// <summary>
        /// <para type="description">Collection of group identifiers.</para>
        /// <para type="description">
        /// Groups listed will be either Added, Removed or replace the current list of group
        /// membership based on GroupAction parameter.
        /// </para>
        /// </summary>
        [Parameter(ValueFromPipelineByPropertyName = true)]
        public string[] Groups { get => _groups; set => _groups = CreateArray(value); }

        /// <summary>
        /// <para type="description">
        /// Each application is assigned to one primary category based on its most defining aspect.
        /// </para>
        /// </summary>
        [Parameter(ValueFromPipelineByPropertyName = true)]
        public string PrimaryCategory { get; set; }

        /// <summary>
        /// <para type="description">Action to take with URLs.</para>
        /// </summary>
        [Parameter]
        public MembershipActions UrlAction { get; set; } = MembershipActions.Replace;

        /// <summary>
        /// <para type="description">URLs that determine this particular application.</para>
        /// </summary>
        [Parameter(ValueFromPipelineByPropertyName = true)]
        public string[] UrlList { get => _urlList; set => _urlList = CreateArray(value); }

        /// <summary>
        /// <para type="description">
        /// States whether the URL is defined as a Regular Expression or not.
        /// </para>
        /// </summary>
        [Parameter]
        public SwitchParameter UrlsDefinedAsRegularExpression { get; set; }

        /// <inheritdoc />
        protected override string InputName => nameof(ApplicationSite);

        #endregion Properties

        #region Methods

        /// <inheritdoc />
        protected override async Task Set(string value)
        {
            var o = Session.UpdateApplicationSite(value);
            UpdateProperties(o);
            await o.AcceptChanges(Ignore, cancellationToken: CancelProcessToken);
            WriteObject(o);
        }

        /// <inheritdoc />
        protected override bool UpdateProperty(IObjectSummary obj, string name, object value)
        {
            if (base.UpdateProperty(obj, name, value)) return true;

            var o = (Koopman.CheckPoint.ApplicationSite)obj;
            switch (name)
            {
                case nameof(AdditionalCategoriesAction):
                    if (AdditionalCategoriesAction == MembershipActions.Replace && AdditionalCategories == null)
                        o.AdditionalCategories.Clear();
                    return true;

                case nameof(AdditionalCategories):
                    o.AdditionalCategories.Add(AdditionalCategoriesAction, AdditionalCategories);
                    return true;

                case nameof(ApplicationSignatureAction):
                    if (ApplicationSignatureAction == MembershipActions.Replace && ApplicationSignature == null)
                        o.ApplicationSignature.Clear();
                    return true;

                case nameof(ApplicationSignature):
                    o.ApplicationSignature.Add(ApplicationSignatureAction, Groups);
                    return true;

                case nameof(GroupAction):
                    if (GroupAction == MembershipActions.Replace && Groups == null)
                        o.Groups.Clear();
                    return true;

                case nameof(Groups):
                    o.Groups.Add(GroupAction, Groups);
                    return true;

                case nameof(UrlAction):
                    if (UrlAction == MembershipActions.Replace && UrlList == null)
                        o.UrlList.Clear();
                    return true;

                case nameof(UrlList):
                    o.UrlList.Add(UrlAction, UrlList);
                    return true;

                default:
                    return false;
            }
        }

        #endregion Methods
    }
}